; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

#include <Arduino.h> // Required for PlatformIO
#include <WiFi.h>
#include <ESPAsyncWebServer.h>
#include <AsyncTCP.h>

[env:uno_r4_wifi]
platform = renesas-ra
board = uno_r4_wifi
framework = arduino
monitor_speed = 115200

lib_deps =
    # The official WiFi library for R4 is built-in, 
    # but we need to point to the LX16A library
    https://github.com/alecxcode/LX16A-bus.git
    arduino-libraries/Servo @ ^1.2.1

; This prevents the conflict between the standard WebServer and the Async version
lib_ignore = 
    WebServer
    WiFiServer